alertTitle: "Alert"
alertVerticalOffset: 0.0
minutesPerHeartbeat: 1.0
showDialogOnDelete: true
openBrowserOnStart: false
showTrayIcon: true
sequentialSoundInterval: 1.0
showExampleAlertOnStart: true
initialSoundFolder: "/home/adarw"
alertDefaultSoundFile: ""
secondsUntilAlertDisappear: 30
timeFieldPlacementInAlert: 1
descFieldName: "Subject"
charsToBreakAfter: 30
alertBgColor: "#bed6c5"
alertOpacity: 80
gmt: 2
daylightSaving: false
screenSize:
  width: 1920.0
  height: 1080.0
ImpactFieldColoring: "Importance"
remindBefore1:
  minutesBeforeAlert: 15.0
  alertTitle: "Early Alert"
  secondsUntilAlertDisappear: 30
  soundPath: ""
  enabled: true
remindBefore2:
  minutesBeforeAlert: 5.0
  alertTitle: "Early Alert"
  secondsUntilAlertDisappear: 30
  soundPath: ""
  enabled: true
importMappings:
- templateName: "Importance"
  csvName: "Level"
