alertTitle: "Alert"
alertVerticalOffset: 40.0
minutesPerHeartbeat: 1.0
showDialogOnDelete: true
openBrowserOnStart: false
showTrayIcon: true
sequentialSoundInterval: 1.0
initialSoundFolder: "C:\\Users\\Erez"
alertDefaultSoundFile: ""
secondsUntilAlertDisappear: 30
timeFieldPlacementInAlert: 1
ImpactFieldColoring: "Impact"
remindBefore1:
  minutesBeforeAlert: 15.0
  alertTitle: "Early Alert 1"
  secondsUntilAlertDisappear: 30
  soundPath: ""
  enabled: true
remindBefore2:
  minutesBeforeAlert: 5.0
  alertTitle: "Early Alert 2"
  secondsUntilAlertDisappear: 30
  soundPath: ""
  enabled: true
importMappings:
- templateName: "Impact"
  csvName: "Impact"
- templateName: "Currency"
  csvName: "Currency"
- templateName: "Subject"
  csvName: "Name"
